#AWS-cloudformation template for creating a simple S3 bucket from custom template

#example1 (without versioning)
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
       BucketName: for-s3-yogitestingewithversioning
#
#########################################
#example2(with versioning)
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
       BucketName: for-s3-yogitestingewithversioning
       VersioningConfiguration:
        Status: Enabled
#when you a resouce using a template, if some user had a change with that resource. as a devops engineer you need to detect those changes
#Goto stack-> stack actions-> Detect drift
#if someone might had a changed anything you can  see DRIFT status = Drifted
#Drift-> select a resouce -> view Drift details.
 
