#AWS-cloudformation template for creating a simple S3 bucket from custom template

#example1 (without versioning)
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
       BucketName: for-s3-yogitestingewithversioning


#example2(with versioning)
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
       BucketName: for-s3-yogitestingewithversioning
       VersioningConfiguration:
        Status: Enabled
